'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AssignReview

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblReviewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''reviewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reviewTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAssignBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAssignBranch As Global.AjaxControlToolkit.ComboBox

    '''<summary>
    '''valcboAssignBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valcboAssignBranch As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboToDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboToDepartment As Global.AjaxControlToolkit.ComboBox

    '''<summary>
    '''valcboToDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valcboToDepartment As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboToEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboToEmployee As Global.AjaxControlToolkit.ComboBox

    '''<summary>
    '''valcboToEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valcboToEmployee As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtReviewFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReviewFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFrom As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ajtCalFilterFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajtCalFilterFrom As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtReviewTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReviewTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnTo As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ajtCalFilterTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajtCalFilterTo As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''valtxtReviewFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtReviewFrom As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valtxtReviewTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtReviewTo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInstruction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valtxtInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtInstruction As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAssign As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdAssignList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAssignList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnSaveAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAssignment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAssignment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''prgLoadingProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prgLoadingProgress As Global.System.Web.UI.UpdateProgress
End Class
