'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RecordReview

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblReviewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboReviewBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboReviewBranch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''reviewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reviewTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cpFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpFilter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFilterLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilterLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cpFilberBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpFilberBody As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtFilterReviewFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFilterReviewFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnFilterFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFilterFrom As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ajtCalFilterFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajtCalFilterFrom As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtFilterReviewTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFilterReviewTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnFilterTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFilterTo As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ajtCalFilterTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajtCalFilterTo As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnApplyReviewFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyReviewFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CollapsiblePanelExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtender1 As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''cboSearchOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSearchOption As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSearchReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchReview As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdReviews As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdSubmittedReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSubmittedReviews As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''findingTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents findingTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectedReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedReview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mvFindings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvFindings As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vFindingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFindingList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''btnAddNewFinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewFinding As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dlFindingSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlFindingSummary As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''vAddEditFinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditFinding As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtFindingNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFindingNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFndReviewArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFndReviewArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboRiskLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRiskLevel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboRiskCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRiskCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboRiskSubCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRiskSubCategory As Global.AjaxControlToolkit.ComboBox

    '''<summary>
    '''cboManageAwareness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboManageAwareness As Global.AjaxControlToolkit.ComboBox

    '''<summary>
    '''pnlFndObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFndObservation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblObservationPanelTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservationPanelTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mlvFndObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mlvFndObservation As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vFndObservationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFndObservationList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''btnAddFndObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddFndObservation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dtlFndObservationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtlFndObservationList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''vFndAddObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFndAddObservation As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtFndObservationNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFndObservationNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFndObservationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFndObservationDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnFndObsDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFndObsDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''calFndObservationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calFndObservationDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtFndObservationDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFndObservationDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFndObservationRootCauseAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFndObservationRootCauseAnalysis As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtFndObservationImplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFndObservationImplication As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valtxtFndObservationImplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtFndObservationImplication As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtFndObservationAssumptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFndObservationAssumptions As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFndObservationMitigationControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFndObservationMitigationControl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboFndObservationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFndObservationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''mlvFndRecomms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mlvFndRecomms As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vFndRecommsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFndRecommsList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''btnAddFndRecomm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddFndRecomm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dtlFndRecommList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtlFndRecommList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''vFndAddRecomms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFndAddRecomms As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlFndRecomms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFndRecomms As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRecommendationPanelTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecommendationPanelTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRecommendation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecommendation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valtxtRecommendation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtRecommendation As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnSaveFindingRecomms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveFindingRecomms As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelFindingRecomms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelFindingRecomms As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFndSaveObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFndSaveObservation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFndCancelObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFndCancelObservation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveFinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveFinding As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelFinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelFinding As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCommintChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCommintChanges As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hndBnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hndBnt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpUploadFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpUploadFile As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlUploadFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUploadFile As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFileUploadTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileUploadTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ucUploadFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucUploadFile As Global.FRITS.ucAsyncFileUploadControl

    '''<summary>
    '''btnCancelUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbtnShowUploadFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnShowUploadFiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpShowUploadedFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpShowUploadedFiles As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlShowFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShowFiles As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblViewFilesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewFilesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ucViewFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucViewFiles As Global.FRITS.ucFileListControl

    '''<summary>
    '''btnClsShowFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClsShowFiles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''prgLoadingProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prgLoadingProgress As Global.System.Web.UI.UpdateProgress
End Class
