'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SystemSetup

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblSystemSetupTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSystemSetupTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnObservationStatusSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnObservationStatusSetup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRistkLevelSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRistkLevelSetup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRiskCategorySetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRiskCategorySetup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblActiveViewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveViewTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mlvSystemSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mlvSystemSetup As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vObservationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vObservationStatus As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''mvObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvObservation As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vObservationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vObservationList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''btnAddObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddObservation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdObservationStatuses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdObservationStatuses As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''vAddEditObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditObservation As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''aeObservationTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aeObservationTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtObservationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservationStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valObserveStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valObserveStatus As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtObservationStatusCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservationStatusCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valObserveStausCoode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valObserveStausCoode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtObservationNarration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservationNarration As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valtxtObservationNarration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtObservationNarration As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboObserveStausEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboObserveStausEnabled As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSaveObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveObservation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelObservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelObservation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vRiskLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vRiskLevels As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''mvRiskLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvRiskLevels As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vRiskLevelList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vRiskLevelList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''btnAddRiskLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRiskLevel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdRiskLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRiskLevels As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''vAddEditRiskLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditRiskLevel As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''aeRiskLevelTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aeRiskLevelTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRiskLevelDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRiskLevelDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valTxtRiskLevelDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valTxtRiskLevelDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtRiskLevelScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRiskLevelScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valtxtRiskLevelScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtRiskLevelScore As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnSaveRiskLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveRiskLevel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelRiskLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelRiskLevel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vRiskCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vRiskCategories As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''mlvCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mlvCategories As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vRiskCategoryList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vRiskCategoryList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''btnAddRiskCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRiskCategory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdRiskCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRiskCategories As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''vAddEditRiskCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditRiskCategory As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''aeRiskCategoryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aeRiskCategoryTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRiskCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRiskCategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valTxtRiskCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valTxtRiskCategory As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnSaveRiskCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveRiskCategory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelRiskCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelRiskCategory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''prgLoadingProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prgLoadingProgress As Global.System.Web.UI.UpdateProgress
End Class
