'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UpdateReviewRecord

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblReviewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mlvBranchRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mlvBranchRecords As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''cpFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpFilter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFilterLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilterLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cpFilberBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpFilberBody As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtFilterReviewFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFilterReviewFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnFilterFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFilterFrom As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ajtCalFilterFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajtCalFilterFrom As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtFilterReviewTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFilterReviewTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnFilterTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFilterTo As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ajtCalFilterTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajtCalFilterTo As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnApplyReviewFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyReviewFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CollapsiblePanelExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtender1 As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''cboSearchOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSearchOption As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSearchReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchReview As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdReviews As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblSelectedReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedReview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mvFindings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvFindings As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vFindingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFindingList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''dlFindingSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlFindingSummary As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''vAddEditFinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditFinding As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pFindingNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pFindingNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pReviewArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pReviewArea As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtlFndObservationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtlFndObservationList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''btnHndBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHndBtn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpAddActionTaken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpAddActionTaken As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlAddEditActionTaken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddEditActionTaken As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtATDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtATDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnATDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnATDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''valtxtATDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtATDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtATDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtATDetails As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboATtatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboATtatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''valATDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valATDetails As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnSaveActionTaken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveActionTaken As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelActionTaken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelActionTaken As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hndBnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hndBnt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpAddEditActionPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpAddEditActionPlan As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlAddEditActionPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddEditActionPlan As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hndAPObservationId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hndAPObservationId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblAPObservationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAPObservationDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAPObservationNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAPObservationNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAPObservationDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAPObservationDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAPResolutionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAPResolutionDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnAPResolutionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAPResolutionDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''calAPResolutionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calAPResolutionDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''cboUsersInBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboUsersInBranch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnAddActionPlanEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddActionPlanEmployee As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAPUserList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAPUserList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtAPSchedOfficerResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAPSchedOfficerResponse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAPDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAPDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valtxtAPDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtAPDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnSaveActionPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveActionPlan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtAPSelectedEmpIds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAPSelectedEmpIds As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''prgLoadingProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prgLoadingProgress As Global.System.Web.UI.UpdateProgress
End Class
