'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewUpdateReview

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblReviewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectedReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedReview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnGoBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mvFindings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvFindings As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vFindingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFindingList As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''dlFindingSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlFindingSummary As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''vAddEditFinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditFinding As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pFindingNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pFindingNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pReviewArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pReviewArea As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pRiskLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pRiskLevel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pRiskCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pRiskCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pRiskSubCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pRiskSubCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pManagementAwareness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pManagementAwareness As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtlFndObservationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtlFndObservationList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''hndBnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hndBnt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpUpdateManagementResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpUpdateManagementResponse As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlUpdateManagementResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUpdateManagementResponse As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtManagementResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManagementResponse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveManagementResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveManagementResponse As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelManagementResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelManagementResponse As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hndBnt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hndBnt1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpUpdateObservationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpUpdateObservationStatus As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUpdateStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtUODescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUODescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUOImplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUOImplication As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUORootCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUORootCause As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUOAssumption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUOAssumption As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUOMitigatingControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUOMitigatingControl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUO1stRecommendation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUO1stRecommendation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboObservationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboObservationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSaveStatusChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveStatusChange As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCloseUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseUpdateStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cfHndBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cfHndBtn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpCreateFollowUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpCreateFollowUp As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlCreateFollowUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCreateFollowUp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtFUDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFUDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnFUDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFUDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''valtxtFUDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valtxtFUDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtFUTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFUTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboFUCurrentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFUCurrentStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFURemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFURemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveFollowUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveFollowUp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCloseFollowUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseFollowUp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbtnShowUploadFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnShowUploadFiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpShowUploadedFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpShowUploadedFiles As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlShowFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShowFiles As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblViewFilesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewFilesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ucViewFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucViewFiles As Global.FRITS.ucFileListControl

    '''<summary>
    '''btnClsShowFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClsShowFiles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''prgLoadingProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prgLoadingProgress As Global.System.Web.UI.UpdateProgress
End Class
