'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProfileManager_Default

    '''<summary>
    '''frm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''pnlContentPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlContentPane As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabStrip As Global.ComponentArt.Web.UI.TabStrip

    '''<summary>
    '''MultiPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiPage As Global.ComponentArt.Web.UI.MultiPage

    '''<summary>
    '''PageviewGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageviewGeneral As Global.ComponentArt.Web.UI.PageView

    '''<summary>
    '''lstApplicationPartsCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstApplicationPartsCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''lstApplicationParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstApplicationParts As Global.ComponentArt.Web.UI.TreeView

    '''<summary>
    '''cmdCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''lstAuthorisedOperatorsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAuthorisedOperatorsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lstAuthorisedOperatorsCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAuthorisedOperatorsCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''lstAuthorisedOperators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAuthorisedOperators As Global.ComponentArt.Web.UI.TreeView

    '''<summary>
    '''PermissionsCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PermissionsCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''PermissionsPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PermissionsPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''divPermissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPermissions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divChange As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkChange As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCreate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCreate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDelete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDelete As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divRead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRead As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkRead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRead As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUpload As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUpload As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSubmit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSubmit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCancel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCancel As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divAuthorize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAuthorize As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkAuthorize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAuthorize As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divDecline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDecline As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkDecline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDecline As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRelease As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRelease As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divReverse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReverse As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkReverse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReverse As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divCommit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCommit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkCommit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCommit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divManage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divManage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkManage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkManage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divGenerate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGenerate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkGenerate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGenerate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPrint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrint As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExport As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkList As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSend As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSend As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divScan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkScan As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCheck As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCheck As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divActivate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divActivate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkActivate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActivate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReset As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOrder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOrder As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divReceive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReceive As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkReceive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReceive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSearch As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PermissionCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PermissionCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''PageviewUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageviewUsers As Global.ComponentArt.Web.UI.PageView

    '''<summary>
    '''lstUsersCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstUsersCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''tbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtSearchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchUser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstUsers As Global.ComponentArt.Web.UI.TreeView

    '''<summary>
    '''PageviewGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageviewGroups As Global.ComponentArt.Web.UI.PageView

    '''<summary>
    '''lstGroupsCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstGroupsCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''lstGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstGroups As Global.ComponentArt.Web.UI.TreeView

    '''<summary>
    '''PageviewRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageviewRoles As Global.ComponentArt.Web.UI.PageView

    '''<summary>
    '''lstRolesCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRolesCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''lstRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRoles As Global.ComponentArt.Web.UI.TreeView

    '''<summary>
    '''PageviewOrganizationalUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageviewOrganizationalUnits As Global.ComponentArt.Web.UI.PageView

    '''<summary>
    '''lstOrganizationalUnitsCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstOrganizationalUnitsCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''lstOrganizationalUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstOrganizationalUnits As Global.ComponentArt.Web.UI.TreeView

    '''<summary>
    '''PageviewAuditLogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageviewAuditLogs As Global.ComponentArt.Web.UI.PageView

    '''<summary>
    '''gridCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCallBack As Global.ComponentArt.Web.UI.CallBack

    '''<summary>
    '''Grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid As Global.ComponentArt.Web.UI.Grid

    '''<summary>
    '''applicationPartsMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents applicationPartsMenu As Global.ComponentArt.Web.UI.Menu

    '''<summary>
    '''authorisedOperatorsMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents authorisedOperatorsMenu As Global.ComponentArt.Web.UI.Menu

    '''<summary>
    '''usersMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usersMenu As Global.ComponentArt.Web.UI.Menu

    '''<summary>
    '''groupsMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupsMenu As Global.ComponentArt.Web.UI.Menu

    '''<summary>
    '''rolesMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rolesMenu As Global.ComponentArt.Web.UI.Menu

    '''<summary>
    '''organizationalUnitsMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents organizationalUnitsMenu As Global.ComponentArt.Web.UI.Menu

    '''<summary>
    '''GridContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridContextMenu As Global.ComponentArt.Web.UI.Menu

    '''<summary>
    '''LogSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ltlUserScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlUserScript As Global.System.Web.UI.WebControls.Literal
End Class
